### PR TITLE
feat: add Mobius Loop hooks (loop-detector, definition-gates)

### LINKED ISSUE #1177: [Bug]: infinite loop
### Prerequisites

- [x] I have searched existing issues to avoid duplicates
- [x] I am using the latest version of oh-my-opencode
- [x] I have read the [documentation](https://github.com/code-yeongyu/oh-my-opencode#readme)

### Bug Description

  ┃  [SYSTEM DIRECTIVE: OH-MY-OPENCODE - BOULDER CONTINUATION]                                                                                                                                                                                                              
  ┃                                                                                                                                                                                                                                                                         
  ┃  You have an active work plan with incomplete tasks. Continue working.                                                                                                                                                                                                  
  ┃                                                                                                                                                                                                                                                                         
  ┃  RULES:                                                                                                                                                                                                                                                                 
  ┃  - Proceed without asking for permission                                                                                                                                                                                                                                
  ┃  - Mark each checkbox [x] in the plan file when done                                                                                                                                                                                                                    
  ┃  - Use the notepad at .sisyphus/notepads/service-fee-no-return-record/ to record learnings                                                                                                                                                                              
  ┃  - Do not stop until all tasks are complete                                                                                                                                                                                                                             
  ┃  - If blocked, document the blocker and move to the next task                                                                                                                                                                                                           
  ┃                                                                                                                                                                                                                                                                         
  ┃  [Status: 11/38 completed, 27 remaining]    

### Steps to Reproduce

When the task was completed, only the first level was checked, and the second level was not checked, resulting in an incorrect quantity.

### Expected Behavior

Check Level 2 and have a reflection mechanism when stuck in an infinite loop

### Actual Behavior

When tasks have a hierarchical relationship, completing the task without checking the second level will cause the child process to repeatedly reply that it is completed, and the main process to repeatedly reply that it is not completed and requires completion.

### Doctor Output

```shell
I can't output what I need normally

PS C:\Users\aiguo> bunx oh-my-opencode doctor
============================================================
Bun v1.3.6 (d530ed99) Windows x64
Windows v.win10_rs5
Args: "C:\Users\aiguo\AppData\Local\Temp\bunx-2301971004-oh-my-opencode@latest\node_modules\oh-my-opencode-windows-x64\bin\oh-my-opencode.exe" "doctor"  
Features: jsc no_avx2 no_avx standalone_executable
Builtins: "bun:main"
Elapsed: 63ms | User: 15ms | Sys: 78ms
RSS: 101.57MB | Peak: 101.57MB | Commit: 0.15GB | Faults: 25006 | Machine: 34.19GB

CPU lacks AVX support. Please consider upgrading to a newer CPU.
panic(main thread): Segmentation fault at address 0xFFFFFFFFFFFFFFFF
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.3.6/w_1d530ed9EggggigDoujp1Bqooo1Bm1no1Bq9mo1Bgpsl1Biswl1Bqgo62B2un62Bizgx2Byjgx2B+/lm2Bisy/2Bs8t32Bsh67vBy2w+vB657rwB__qy5ouCA2DD
```

### Error Logs

```shell

```

### Configuration

```json

```

### Additional Context

_No response_

### Operating System

Windows

### OpenCode Version

1.1.36

### LINKED ISSUE #1178: [Bug]: Plan mode keeps looping endlessly, unable to exit
### Prerequisites

- [x] I have searched existing issues to avoid duplicates
- [x] I am using the latest version of oh-my-opencode
- [x] I have read the [documentation](https://github.com/code-yeongyu/oh-my-opencode#readme)

### Bug Description

Image

### Steps to Reproduce

Execute under Atlas

### Expected Behavior

The plan should finish

### Actual Behavior

The plan loops endlessly and never finishes

### Doctor Output

```shell
[SYSTEM DIRECTIVE: OH-MY-OPENCODE - BOULDER CONTINUATION]

You have an active work plan with incomplete tasks. Continue working.

RULES:
- Proceed without asking for permission
- Mark each checkbox [x] in the plan file when done
- Use the notepad at .sisyphus/notepads/eblog/ to record learnings
- Do not stop until all tasks are complete
- If blocked, document the blocker and move to the next task

[Status: 23/34 completed, 11 remaining]
```

### Error Logs

```shell

```

### Configuration

```json

```

### Additional Context

_No response_

### Operating System

Windows

### OpenCode Version

1.1.36

---
<details>
<summary>Original (auto-translated)</summary>

### Prerequisites

- [x] I have searched existing issues to avoid duplicates
- [x] I am using the latest version of oh-my-opencode
- [x] I have read the [documentation](https://github.com/code-yeongyu/oh-my-opencode#readme)

### Bug Description

Image

### Steps to Reproduce

在Atlas下执行

### Expected Behavior

结束计划

### Actual Behavior

循环计划不结束

### Doctor Output

```shell
[SYSTEM DIRECTIVE: OH-MY-OPENCODE - BOULDER CONTINUATION]

You have an active work plan with incomplete tasks. Continue working.

RULES:
- Proceed without asking for permission
- Mark each checkbox [x] in the plan file when done
- Use the notepad at .sisyphus/notepads/eblog/ to record learnings
- Do not stop until all tasks are complete
- If blocked, document the blocker and move to the next task

[Status: 23/34 completed, 11 remaining]
```

### Error Logs

```shell

```

### Configuration

```json

```

### Additional Context

_No response_

### Operating System

Windows

### OpenCode Version

1.1.36

</details>

### PR DESCRIPTION
**Pull request by agno01**
## Summary

- Add `loop-detector` hook to detect repeated tool calls, repeated tool errors, and read/edit ping-pong loops.
- Add `definition-gates` hook to remind agents about Definition of Ready before delegation and Definition of Done before todo completion.
- Update the branch against current `dev` and fit the hooks into the current 5-tier hook composition.

## Hook Architecture

- `loop-detector`: Session tier, created in `create-session-hooks.ts`, because it tracks session-level tool history and handles `tool.execute.after` error events plus `session.deleted` cleanup through the event dispatcher. It is invoked from `tool.execute.before` and `event`.
- `definition-gates`: Tool Guard tier, created in `create-tool-guard-hooks.ts`, because it guards task delegation and todo completion through `tool.execute.before`.
- Prompt async gate interaction: none. These hooks do not call `session.prompt`, `session.promptAsync`, or `dispatchInternalPrompt`; they only append reminders to hook output and maintain in-memory loop state.

## Changes

- `src/hooks/loop-detector/`: loop detection logic, warnings, error tracking, and tests.
- `src/hooks/definition-gates/`: DoR/DoD checks, reminder formatting, ambiguity/dependency detection, and tests.
- `src/plugin/hooks/create-session-hooks.ts`: wires `loop-detector` into the Session tier.
- `src/plugin/hooks/create-tool-guard-hooks.ts`: wires `definition-gates` into the Tool Guard tier.
- `src/plugin/event-hook-dispatcher.ts` and `src/plugin/tool-execute-before.ts`: dispatch the new hooks in the current refactored plugin architecture.

## Testing

```bash
bun test src/hooks/loop-detector/index.test.ts src/hooks/definition-gates/index.test.ts
bun run typecheck
bun install # completed prepare/build/schema generation successfully
```

## Related Issues

Closes #1177
Closes #1178

### CODE REVIEW

**Comment by agno01** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by agno01** [comment]
recheck

**Comment by agno01** [comment]
```I have read the CLA Document and I hereby sign the CLA```

**Review by code-yeongyu — COMMENTED** [review]
Great feature addition for preventing infinite loops and enforcing quality gates!

**Review notes:**

The Mobius Loop hooks concept is solid:
- **loop-detector**: Good pattern detection for repeated calls, error loops, and ping-pong patterns
- **definition-gates**: DoR/DoD enforcement helps maintain task quality

**cubic identified issues (now resolved in latest commit):**
- The ambiguity regex false positives were fixed
- The hardcoded `dependencies_mapped` was addressed
- Test coverage for recent-history-window was improved

**Questions:**
1. Are these hooks enabled by default, or do users need to opt-in via config?
2. What's the default threshold for loop detection (number of repeated calls before triggering)?
3. Is there a way to customize the DoR/DoD checklists per project?

Overall this looks good. Once the questions above are clarified, I'm happy to approve.

**Review by code-yeongyu — APPROVED** [review]
Approving this feature addition. The Mobius Loop hooks (loop-detector, definition-gates) are well-implemented.

**Summary:**
- loop-detector prevents infinite tool loops (repeated calls, error loops, ping-pong patterns)
- definition-gates enforces DoR before delegation and DoD reminders on completion
- cubic review passed on latest commit (5/5 confidence)
- CLA signed
- 18 tests passing

The hooks address real problems (#1177, #1178) with token-wasting infinite loops.

**Note for docs:** Consider adding a brief section in configurations.md about these new hooks once merged.

**Comment by agno01** [comment]
Thanks for the review and approval! Answering your questions:

**1. Are these hooks enabled by default?**

Yes, both hooks are **enabled by default**. The `isHookEnabled()` function checks if a hook is NOT in `disabledHooks`, so all hooks are active unless explicitly disabled.

Users can opt-out via config:
```json
{
  "disabled_hooks": ["loop-detector", "definition-gates"]
}
```

**2. What's the default threshold for loop detection?**

From `LOOP_THRESHOLDS`:
- **Repeated calls**: 3 identical tool calls (same tool + same args)
- **Error loop**: 2 consecutive same error messages
- **Ping-pong pattern**: 6 alternating calls (e.g., read-edit-read-edit-read-edit)
- **History window**: Only considers last 10 calls

**3. Is there a way to customize the DoR/DoD checklists per project?**

Not currently. The checklists are hardcoded in `formatCriterion()`. If there's demand for customization, we could extend the config schema in a follow-up PR to allow per-project overrides.

---

Let me know if you'd like any changes before merge!

**Comment by code-yeongyu** [comment]
@sisyphus-dev-ai please review this PR

**Comment by sisyphus-dev-ai** [comment]
## Code Review: Mobius Loop Hooks (loop-detector, definition-gates)

**Reviewer:** @sisyphus-dev-ai

---

### Summary

This PR adds two new hooks to prevent infinite loops and enforce quality gates:
- **loop-detector**: Detects repeated calls, error loops, and ping-pong patterns
- **definition-gates**: Enforces Definition of Ready (DoR) before delegation and Definition of Done (DoD) reminders on completion

The feature addresses real problems documented in #1177 and #1178.

---

### Review Findings

#### Critical Issue: TypeScript Import Errors

The new hooks have **TypeScript compilation errors** that need to be fixed:

```
src/hooks/definition-gates/index.ts(1,28): error TS2305: Module '"@opencode-ai/plugin"' has no exported member 'PreToolUseInput'.
src/hooks/definition-gates/index.ts(1,45): error TS2305: Module '"@opencode-ai/plugin"' has no exported member 'PreToolUseOutput'.
src/hooks/loop-detector/index.ts(1,28): error TS2305: Module '"@opencode-ai/plugin"' has no exported member 'PreToolUseInput'.
src/hooks/loop-detector/index.ts(1,45): error TS2305: Module '"@opencode-ai/plugin"' has no exported member 'PreToolUseOutput'.
```

**Root Cause:** The hooks incorrectly import `PreToolUseInput` and `PreToolUseOutput` from `@opencode-ai/plugin`, but these types don't exist in that module.

**Fix Required:** Follow the pattern used by other hooks (e.g., `comment-checker`, `prometheus-md-only`) which define inline types:

```typescript
// Instead of:
import type { PluginInput, PreToolUseInput, PreToolUseOutput } from "@opencode-ai/plugin"

// Use:
import type { PluginInput } from "@opencode-ai/plugin"

// And define inline types for the hook signatures:
"tool.execute.before": async (
  input: { tool: string; sessionID: string; callID: string },
  output: { args: Record<string, unknown>; message?: string }
): Promise<void> => {
```

Or, for loop-detector which needs `tool.name` and `tool.input`:

```typescript
"tool.execute.before": async (
  input: { tool: { name: string; input?: Record<string, unknown> }; sessionID?: string },
  output: { output?: string }
): Promise<typeof output> => {
```

---

#### cubic-identified Issues (Verified Resolved)

1. **Ambiguity regex false positives** - ✅ Fixed in `e7b95fa`
   - Changed from `/(maybe|perhaps|possibly|or|unclear)/i` to proper word boundaries with exclusions

2. **Hardcoded `dependencies_mapped`** - ✅ Fixed in `e7b95fa`
   - Now properly detects dependency mentions in prompts

3. **Test coverage for recent-history-window** - ✅ Fixed in `86711df`
   - Test now properly creates a loop pattern in old history

---

#### Tests

- **18 tests passing** across both hooks
- Good BDD-style test structure with `//#given`, `//#when`, `//#then` comments
- Test coverage is comprehensive for core detection logic

---

#### Integration

- Hooks are properly registered in `src/index.ts`
- Hook names added to `HookNameSchema` in `src/config/schema.ts`
- Exports added to `src/hooks/index.ts`
- Execution order is correct (loop-detector and definition-gates run after atlas)

---

#### Minor Observations

1. **Unused function `argsEqual`** in loop-detector (line 44-52) - could be removed or used
2. **`loopDetectedAt` field** in `SessionLoopState` is defined but never set
3. The `createDoDReminder` function is defined but currently unused (only the inline DoD reminder string is used in the hook)

---

### Verdict

**Request Changes** - The TypeScript import errors must be fixed before merge. The tests pass in isolation but the project won't compile.

Once the import errors are fixed, this is a solid feature addition with well-thought-out detection logic and proper test coverage.

---

### Quick Fix Reference

For **loop-detector/index.ts**:
```typescript
// Line 1 - Remove PreToolUseInput, PreToolUseOutput from import
import type { PluginInput } from "@opencode-ai/plugin"

// Lines 169-175 - Update interface
export interface LoopDetectorHook {
  "tool.execute.before": (
    input: { tool: { name: string; input?: unknown }; sessionID?: string },
    output: { output?: string }
  ) => Promise<{ output?: string }>
  event: (input: { event: { type: string; properties?: unknown } }) => Promise<void>
}

// Lines 179-182 - Update implementation signature accordingly
```

For **definition-gates/index.ts**:
```typescript
// Line 1 - Remove PreToolUseInput, PreToolUseOutput from import
import type { PluginInput } from "@opencode-ai/plugin"

// Lines 157-162 - Update interface
export interface DefinitionGatesHook {
  "tool.execute.before": (
    input: { tool: { name: string; input?: unknown }; sessionID?: string },
    output: { output?: string }
  ) => Promise<{ output?: string }>
}

// Lines 166-169 - Update implementation signature accordingly
```

**Comment by code-yeongyu** [comment]
@agno01 Thanks for this feature! However, @sisyphus-dev-ai identified a critical issue:

**TypeScript Import Errors**

```
src/hooks/definition-gates/index.ts(1,28): error TS2305: Module '@opencode-ai/plugin' has no exported member 'PreToolUseInput'.
src/hooks/definition-gates/index.ts(1,45): error TS2305: Module '@opencode-ai/plugin' has no exported member 'PreToolUseOutput'.
src/hooks/loop-detector/index.ts(1,28): error TS2305: Module '@opencode-ai/plugin' has no exported member 'PreToolUseInput'.
src/hooks/loop-detector/index.ts(1,45): error TS2305: Module '@opencode-ai/plugin' has no exported member 'PreToolUseOutput'.
```

**Fix:** Follow the pattern used by other hooks (comment-checker, prometheus-md-only) which define inline types instead of importing non-existent types from @opencode-ai/plugin.

Please update the imports and type definitions as suggested in sisyphus-dev-ai's review above, then we can merge!

**Comment by sisyphus-dev-ai** [comment]
## TypeScript Import Errors Fixed

@agno01 I've implemented the fix for the TypeScript import errors. Since this PR is from a fork, I've pushed the fix to our repo:

**Commit:** [`c567a81`](https://github.com/code-yeongyu/oh-my-opencode/commit/c567a81)

### Changes Made

**1. Removed invalid imports:**
```typescript
// Before (line 1 in both files):
import type { PluginInput, PreToolUseInput, PreToolUseOutput } from "@opencode-ai/plugin"

// After:
import type { PluginInput } from "@opencode-ai/plugin"
```

**2. Updated type definitions to match the actual hook API:**

The hooks were using `input.tool.name` and `input.tool.input`, but the actual API passes:
- `input.tool` as a string (tool name directly)
- `output.args` for tool arguments

```typescript
// Before:
export interface LoopDetectorHook {
  "tool.execute.before": (
    input: PreToolUseInput,
    output: PreToolUseOutput
  ) => Promise<PreToolUseOutput>
}

// After:
export interface LoopDetectorHook {
  "tool.execute.before": (
    input: { tool: string; sessionID: string; callID: string },
    output: { args: Record<string, unknown>; output?: string }
  ) => Promise<{ args: Record<string, unknown>; output?: string }>
}
```

**3. Updated implementation to use correct API:**
```typescript
// Before:
const toolName = input.tool.name
const toolArgs = (input.tool.input ?? {}) as Record<string, unknown>

// After:
const toolName = input.tool
const toolArgs = (output.args ?? {}) as Record<string, unknown>
```

### Verification
- Typecheck: PASS
- Tests: 18/18 passing
- Build: SUCCESS

---

@agno01 You have two options:

1. **Cherry-pick my commit** into your branch:
   ```bash
   git fetch upstream
   git cherry-pick c567a81
   git push
   ```

2. **Or apply the diff manually** - I can provide a patch file if needed.

Once the fix is applied, this PR should be ready to merge!

**Comment by agno01** [comment]
@sisyphus-dev-ai cherry-picked & merged, pls recheck 👍

**Comment by code-yeongyu** [comment]
@agno01 Thanks for this valuable contribution!

The feature is approved and addresses real infinite-loop bugs. However, PR is showing CONFLICTING because dev has advanced 171 commits ahead with new hooks (stop-continuation-guard, unstable-agent-babysitter, tasks-todowrite-disabler).

Next Steps:
1. Rebase this branch on latest dev: git rebase origin/dev
2. Resolve any merge conflicts (should be straightforward - different hooks)
3. Force push to update PR: git push --force-with-lease

Once rebased and CI passes, we can merge! Feel free to ask if you need help with the rebase.

**Comment by agno01** [comment]
@code-yeongyu conflicts resolved - ready to merge! 👍

**Comment by agno01** [comment]
## Issue Analysis

This PR directly addresses **#1349** and may help several other open issues related to infinite loops.

---

### Fixes #1349
**[Bug]: Sisyphus-Junior stuck in infinite loop endlessly refactoring Python type hints**

The `loop-detector` hook addresses all three patterns described in the issue:

| Issue Pattern | Detection Mechanism |
|---------------|---------------------|
| "Code → LSP → Code" ping-pong cycle | `alternating_pattern` - detects 6+ read-edit alternations |
| Repeatedly switching `dict` ↔ `Dict` | `repeated_call` - catches 3+ identical tool+args calls |
| Same Pyright error persisting | `error_loop` - triggers on 2+ identical errors |

The hook issues warnings with actionable recommendations ("Try a DIFFERENT approach") and escalates after 3 warnings.

---

### May Help

#### #735 - Tool call JSON parse error causes infinite retry loop
**Relevance**: The `error_loop` detection (threshold: 2 same errors) would catch repeated tool calls failing with the same JSON parse error, prompting the agent to stop and fix arguments.

#### #78 - Agents stuck on eternal referencing of patterns  
**Relevance**: The `alternating_pattern` detection may catch excessive search-read cycles when agents repeatedly clone repos looking for patterns. The 6-call threshold could trigger a "Stop and analyze why" warning.

#### #806 - Momus agent enters infinite loop on Windows
**Relevance**: General loop detection applies to any agent behavior. If Momus is cycling through the same tool calls or errors, the hook will detect and warn.

---

### Does NOT Address

- **#1079** - Infrastructure polling loop in `BackgroundManager` (requires code fix in `pollRunningTasks()`, not behavioral detection)
- **#644** - Background task notification loop (UI/state management issue, not agent tool-call behavior)

**Comment by agno01** [comment]
@code-yeongyu I guess it's ready? :)

**Comment by agno01** [comment]
@code-yeongyu please check now

**Comment by code-yeongyu** [comment]
[sisyphus-bot]

## PR Assessment

**Status**: ✅ APPROVED | ✅ CI Passing | ❌ **Merge Conflicts**

**Classification**: FEATURE (not a bugfix)

**Merge Status**: , 

Despite your comment on Feb 2 that conflicts were resolved, the PR still shows merge conflicts with the base branch (). This is blocking merge.

**Action Required**:
1. Fetch latest : 
2. Rebase: Current branch dev is up to date.
3. Resolve any remaining conflicts
4. Force push: 

Once conflicts are truly resolved and CI passes, this feature PR can be merged manually by a maintainer.

---
*Note: This is a feature addition (Mobius Loop hooks), not a bugfix, so auto-merge was not attempted.*

**Comment by agno01** [comment]
@code-yeongyu the conflicts are resolved again 👍

**Comment by code-yeongyu** [comment]
[sisyphus-bot]

PR sweep status check on `dev`.

- Review decision: APPROVED
- Mergeable state: **CONFLICTING** (merge conflict with current `dev`)

Approved but blocked on merge conflicts. Please rebase onto current `dev` and resolve. Once green, the owner can merge.

Assigning `code-yeongyu` for owner visibility on the merge decision.

**Comment by code-yeongyu** [comment]
[sisyphus-bot] Hi agno01. 🙏 Thanks for the Mobius Loop hooks work.

Picking this back up from the 5/16 approval. The PR is large (841/1 across 11 files) and shows CONFLICTING against current `dev`. The hook composition layer has been touched on dev (the 5-tier composition in `AGENTS.md` has been reorganized).

Could you rebase against current `dev` and force-push? After rebase, please confirm in the PR description which tiers the new hooks belong to (Session / ToolGuard / Transform / Continuation / Skill) and whether any interact with the prompt-async-gate. The Mobius Loop concept (loop-detector + definitive-action) is a real safety addition; just needs to fit into the current hook architecture cleanly.

**Comment by agno01** [comment]
@code-yeongyu Should be fixed now 👍

**Comment by code-yeongyu** [comment]
[sisyphus-bot] Thanks @agno01 for the loop-detector and definition-gates ideas. Closing because the branch targets the pre-monorepo tree: the entire plugin source moved to `packages/omo-opencode/src/` (f7e8221a9), dev has since removed the hook enum entries this PR's schema change depends on, and an auto-merged tree would fail to build (`./loop-detector` exports resolve into the relocated layout). If the loop-detection idea still interests you, a redesign against the current 5-tier hook architecture in `packages/omo-opencode/src/hooks/` would be the right starting point.
