### ISSUE TITLE
ast_grep MCP error -32000: Connection closed when upgrade omo to 4.2.2

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [code-yeongyu/oh-my-openagent#4188]
### Prerequisites

- [x] I will write this issue in English (see our [Language Policy](https://github.com/code-yeongyu/oh-my-openagent/blob/dev/CONTRIBUTING.md#language-policy))
- [x] I have searched existing issues to avoid duplicates
- [x] I am using the latest version of oh-my-openagent
- [x] I have read the [documentation](https://github.com/code-yeongyu/oh-my-openagent#readme) or asked an AI coding agent with this project's GitHub URL loaded and couldn't find the answer

### Bug Description

-

### Steps to Reproduce

-

### Expected Behavior

-

### Actual Behavior

-

### Doctor Output

```shell
-
```

### Error Logs

```shell
-
```

### Configuration

```json

```

### Operating System

Windows

### OpenCode Version

1.15.5

**Comment by shudingbo** [comment]
me too, on windows！

**Comment by shudingbo** [comment]
# Bug: LSP MCP `MODULE_NOT_FOUND` — Path Resolution Error for `dist/packages/lsp-tools-mcp/dist/cli.js`

**Version**: oh-my-openagent@4.2.x
**Environment**: Windows (npm global install)

---

## Symptoms

LSP MCP fails to start with the following error:

```
MODULE_NOT_FOUND: Cannot find module 'C:\Users\sdbv\.cache\opencode\packages\oh-my-openagent@^4.2.1\node_modules\oh-my-openagent\dist\packages\lsp-tools-mcp\dist\cli.js'
```

---

## Root Cause Analysis

The path resolution logic in `dist/index.js` (approx. line 133207-133256):

```javascript
// Pseudocode from bundled output
const ownDir = dirname(fileURLToPath(import.meta.url));
// → ".../oh-my-openagent/dist/"

const cliPath = path.join(ownDir, 'packages', 'lsp-tools-mcp', 'dist', 'cli.js');
// → ".../oh-my-openagent/dist/packages/lsp-tools-mcp/dist/cli.js"  ❌ DOES NOT EXIST
```

**Actual file location**:
```
.../oh-my-openagent/packages/lsp-tools-mcp/dist/cli.js  ✅ EXISTS
```

The problem: `import.meta.url` resolves to the `dist/` directory, but `packages/lsp-tools-mcp/dist` lives at the package root (sibling of `dist/`, not inside it).

From the npm package structure:
- `"files"` includes `packages/lsp-tools-mcp/dist`
- `"main"` / `"exports"` point to `dist/index.js`
- But when code starts from `dist/index.js` and resolves relative paths upward, the first candidate `dist/packages/...` does not exist

---

## Workaround

Create a symlink inside the `oh-my-openagent` package directory:

```powershell
# PowerShell (Admin)
cd C:\Users\sdbv\.cache\opencode\packages\oh-my-openagent@^4.2.1\node_modules\oh-my-openagent
New-Item -ItemType Junction -Path "dist\packages" -Target "..\packages"
```

Verify:
```powershell
Test-Path "dist\packages\lsp-tools-mcp\dist\cli.js"  # → True
node dist\packages\lsp-tools-mcp\dist\cli.js --version  # → outputs version
```

Restart opencode after creating the symlink — LSP MCP loads successfully.

---

## Suggested Fix Directions

Add the package root directory (`dirname(dirname(ownDir))`) as a candidate path, or use `createRequire()` to resolve nested package paths properly:

```javascript
// Option 1: Use createRequire
const { createRequire } = require('module');
const cliPath = createRequire(__filename).resolve('lsp-tools-mcp/dist/cli.js');
```

Or fix the existing fallback logic: currently it returns `candidates[0]` which is a non-existent path. It should iterate through all candidates until an actual file is found.

---

**Comment by fjqz177** [comment]
The solution provided would be better if you used this command instead of the one you provided, as your current command will throw an error. Here is my improved command:
```powershell
New-Item -ItemType Junction -Path "dist\packages" -Target (Resolve-Path "packages").Path
```

**Comment by Hoshino-Yumetsuki** [comment]
When I upgrade omo to 1.15.6, the error changed to `ast_grep MCP error -32000: Connection closed`
