### PR TITLE
fix(build): embed shared-session workers in compiled OmO wrappers

### PR DESCRIPTION
**Pull request by code-yeongyu**
## Summary

Include Senpi's shared-session worker in the actual compiled OmO wrapper. The worker path is now tied to an explicit Bun compile root and passed through Senpi's `SENPI_RPC_SESSION_WORKER_ENTRY` build-time contract. The Senpi runtime half is in https://github.com/code-yeongyu/senpi/pull/1499.

Older pinned engines without a session-worker module retain their existing compile graph. This does not change the engine dependency pin, generated JS, runtime environment overrides, or production installations. Based on dev `771b83c298db7d68f5c15accbb771b7dfd86f18a`, preserving #7969 and #7978.

## Changes

- Resolve the published `dist/modes/rpc/session-worker.js` as an additional compile entry.
- Supply an explicit `--root` and matching embedded entry name to Senpi; embedding a worker without matching its runtime path is insufficient.
- Exercise two real Bun workers after relocating a compiled fixture and deleting its complete source tree.

## QA and evidence

All builds/tests ran on approved `mengmotaMac` through Bunshin, using Bun 1.4.2 / macOS arm64. Local commands were source/git/orchestration only.

- `bun run typecheck:script`: passed.
- `bun test script/senpi-worker-compile.test.ts script/build-omo-binary.test.ts script/build-omo-native.test.ts`: **37 passed, 0 failed, 0 skipped in the complete invocation**. Earlier attempts exposed missing source-checkout packaging prerequisites (vendor/ and generated ast-grep skill); those inputs were supplied, not hidden by test edits.
- The real `script/build-omo-binary.ts --target darwin-arm64` pipeline built the plugin, staged 1,183 sidecars, verified embedding and the existing 150 MiB budget, and produced a 151,044,978-byte executable.
- That executable was relocated outside source and driven through shared RPC: two simultaneous sessions, distinct durable identities, real memory/task/LSP registration, requester control, B surviving A close, and both shutdown hooks. Disposable HOME/agent/memory/LSP paths and a loopback dummy model only; owned runtime resources were cleaned.
- Causal RED: even with the new worker compile entry present, the old Senpi runtime still failed `open_session` with `Cannot find module './src/modes/rpc/session-worker.ts'`. The repaired Senpi runtime with the same compile arguments and staged payload passed. The full builder with the latest candidate plugin then passed independently.

Retained evidence: `/tmp/st_01a08205-evidence/remote/` (`st_01a08205-wrapper-red*.log`, `st_01a08205-wrapper-seam-green*.log`, `st_01a08205-wrapper-green.log`, `st_01a08205-omo-full-build.log`, `st_01a08205-omo-build-tests-complete.log`). Source input manifest: `/tmp/st_01a08205-omo-manifest.json`. Final repair handoff: `/tmp/ulw-host-worker-isolation-20260908-result.md`.

## Limits

The actual wrapper was wired to the candidate Senpi dist and its dependency graph in an isolated build tree; the published dependency version has not been bumped. This proves packaging, initialization and RPC lifecycle, not real-provider execution or delegated-task completion. The separate Senpi Node bundle-builder still has its documented three baseline build errors; neither Node dist nor this Bun wrapper result is substituted for that failed gate.

No merge, deployment, or production operation is part of this repair lane.

---
## Summary by cubic
Embeds Senpi's shared-session worker in compiled OmO binaries so the worker path resolves at runtime instead of failing with `Cannot find module './src/modes/rpc/session-worker.ts'`. Older pinned engines without the worker module still compile with the same graph.

- Adds `--root`, a `SENPI_RPC_SESSION_WORKER_ENTRY` define, and `--minify-whitespace` to the Bun compile step, embedding the worker and keeping the binary within the 150 MiB budget.
- Adds tests that compile a binary with the worker, relocate it, delete the source tree, and start two workers; pre-worker engines keep the legacy compile graph.
- No changes to dependency pins, generated JS, or production installations.

<sup>Written for commit 1698c8aa0f098d5b74480656e7375c0bcb2e96f1. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/code-yeongyu/oh-my-openagent/pull/7983?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by code-yeongyu** [comment]
## Final repair handoff (st_01a08205)

Use the paired candidates:

- Senpi #1499: `83cb9c25896bc6f0073e0330da310dccdc982ff2`
- OmO [#7983](https://github.com/code-yeongyu/oh-my-openagent/pull/7983): `8aa771d1d165be93461db3f2b8eb2dece088392d`

Senpi1491/1497/1500 and OmO7969/7978 ancestry is preserved. No generated JS was hand-patched; no production operation, merge, or deployment was performed.

### Observed gates

- Final Senpi tree: **379 passed / 60 RPC files in one invocation**, zero failures.
- Root Senpi check/build and standalone archive/relocation smoke: passed.
- Standalone worker scenarios plus distinct Node-dist case: **9 passed / 4 files**.
- Final OmO builder tests: **37 passed, zero failed/skipped in one invocation**; script typecheck passed.
- The full OmO builder's executable, relocated outside source: two concurrent sessions, distinct durable identities, actual memory/task/LSP registration, control/list, B survives A close, and both shutdown hooks complete.
- Capacity: 1/5/20 admitted; known-path attach at 20 succeeds; allocation 21 rejects; all 20 close replies observed.

All project execution was on approved mengmotaMac through Bunshin, Bun 1.4.2 / Node 26.7.0. The final OmO build's candidate dependency links and embedded codemode source are bound to the matched final Senpi tree.

Final OmO binary: **151,094,514 bytes**; SHA-256 **`81fe131078e4c61ab8d14222e717337ccca0ce69d3695941770f9b6ae19a0096`**. This supersedes the intermediate artifact size in the initial PR description. Embedded runtime manifest: **1,183 entries**, SHA **`3490624cfc997388ae1c900f32f90fd7f31bbf2604d731902fe8298864729bb2`**.

### Do not erase these limits

- The original independent deadline failure remains an actual **341-pass / 1-fail** observation. Its exact unresolved await cannot be recovered from that uninstrumented log. The fixture now controls the request clock after real FIFO entry and bounds/names lifecycle awaits, with the original 60s ceiling unchanged. The final full-suite pass is positive repair evidence, not a retrospective identification of that original await.
- The **separate Node bundle-builder remains failed** with the same three baseline errors (`bun:sqlite`, `type: file`, canvas `.node`). Passing Node dist and Bun artifacts are not substituted for it.
- An extra per-package codemode tsc diagnostic probe reports the same two missing-module declarations on baseline and final; the repository root check passes. No diagnostics were suppressed.

Full report: `/tmp/ulw-host-worker-isolation-20260908-result.md`. Exact source/artifact/runtime manifests and full logs: `/tmp/st_01a08205-evidence/`. The source mirrors and binaries are retained for independent verification; cleanup receipts show no active task-owned processes or recent worker-fixture scratch trees. Both PRs remain open; independent approval is not claimed.

**Comment by code-yeongyu** [comment]
## Bun 1.4.0/Linux and CI attribution repair - final paired heads

- Senpi #1499: **`0a3d6bd8d50ed3c5fd60c05836878c6203df0d05`**
- OmO #7983: **`1698c8aa0f098d5b74480656e7375c0bcb2e96f1`**

### Repaired and verified

1. **Bun 1.4.0 Worker lookup:** reproduced job102172068636 on approved Linux with Bun1.4.0 `34cbb9a40` and Node24.20.0. Relative Worker strings resolve against real cwd; Senpi now passes a URL resolved against compiled `import.meta.url`. OmO's CI/devcontainer policy remains 1.4.0; no version bump or skip.
2. **Installed-package naming:** real Bun-linked packages exposed an additional alias/physical-entry mismatch. The builder now derives the physical worker's embedded name and a compile root containing wrapper and worker. Directory, `.bun` store links, and external development links all pass after deleting their source trees. This is build-time module naming only, not session-path ownership normalization.
3. **Binary budget:** full Linux build initially rejected 163,857,608 bytes. Whitespace-only minification brings the final Linux artifact to 149,599,432 bytes and macOS to 135,556,722 bytes under the unchanged 150 MiB budget.
4. **Changelog attribution:** job102172657732 used synthetic merge0328af6 (new main fe1 plus PR83cb9c2) against event base24891ce83, pulling eleven unrelated package.json paths into the audit. Only the changelog job now checks out the PR head. Actual synthetic-merge RED and final-head GREEN were reproduced; no unrelated tracker docs or waiver were added.

### Final execution evidence

All execution was on approved compute through Bunshin:
- **379 passed / 60 RPC files in one final-SHA invocation**.
- **9 standalone/Node-dist tests passed**; standalone archive/relocation smoke passed.
- **4 Linux Bun1.4.0 layout tests passed**, zero skips.
- **39 macOS Bun1.4.2 builder tests passed**, zero skips.
- **18 script tests passed** and exact-final-head changelog gate passed on Node24.20.0/Linux.
- Full-builder, relocated OmO wrappers with linked installed engines passed two concurrent session opens, real memory/task/LSP registration, control/list, B surviving A close, and both shutdown hooks on Linux and macOS.
- All **5,768 Senpi / 10,452 OmO tracked files** match their final SHAs on both machines. Runtime/worker-dist/artifact manifests and cleanup receipts are retained.

### Remaining cited workspace failure: identified, not hidden

Job102172658271 fails `packages/ai/test/gpt-6-astra-context-window.test.ts:55`: incoming release d5ba44e adds Astra to `opengateway.json` without updating the expected provider list. The same test passes on PR-head inputs (2/2) and fails on both incoming main fe1 and actual merge0328 (1/2). The context-window-value assertion passes. **No AI source/catalog/test is changed in this branch.** Base-owner catalog-test maintenance remains required; other CI jobs keep integration merge checkout, and no all-workspace CI success is claimed.

The separate Node bundle-builder also remains failed with its three documented baseline errors, not substituted by Node-dist/Bun successes. The prior uninstrumented deadline failure's exact await remains retrospectively unknown.

Full report: `/tmp/ulw-host-worker-isolation-20260908-result.md`.
Evidence/manifests: `/tmp/st_01a08205-ci-evidence/`.
Final Linux OmO SHA256: `5fc858f15e48efe8d9fcf972df36fc31075d96bff86258f6138d341e6b207112`.
Final macOS OmO SHA256: `1c6f98c75e352f8b7e88c327b1a542c822b01165be754e2d1d72f39a1d0a724f`.

Both PRs stay open. Owned runtime processes/scratch are cleaned; inactive verification inputs and clean worktrees are retained. No merge, deployment, production operation, or CI polling was performed.

**Comment by code-yeongyu** [comment]
Cross-linked to release dependency-diet tracker #8235; this item is related prior art or a same-root-cause slice, and remains independently open/merged as appropriate.
